version: '3.8'
services:
  be-matadero:
    depends_on:
      - db-matadero
    image: 'matadero-be'
    container_name: 'matadero-be'
    build: .
    ports:
      - '8086:8086'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-matadero:5432/db_matadero
      - SPRING_DATASOURCE_USERNAME=matadero
      - SPRING_DATASOURCE_PASSWORD=matadero123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always
  db-matadero:
    image: postgis/postgis:14-3.2-alpine
#    image: postgres:14-alpine
    container_name: 'matadero-db'
    environment:
      - POSTGRES_USER=matadero
      - POSTGRES_PASSWORD=matadero123
      - POSTGRES_DB=db_matadero
    ports:
      - '5438:5432'
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
  pg-matadero:
    image: dpage/pgadmin4
    container_name: 'matadero-pg'
    ports:
      - "5056:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=matadero@admin.com
      - PGADMIN_DEFAULT_PASSWORD=matadero123
    depends_on:
      - db-matadero
    volumes:
      - pg:/var/lib/pgadmin
    restart: always
  fe-matadero:
    image: 'matadero-fe'
    container_name: 'matadero-fe'
    ports:
      - '4206:80'
    depends_on:
      - be-matadero
    restart: always
volumes:
  db:
  pg: